name: watchlist
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  flutter_bloc: ^8.0.1
  firebase_core: ^1.19.1
  firebase_crashlytics: ^2.8.4
  path_provider: ^2.0.2
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master

  movie:
    path: ../movie
  core:
    path: ../core
  tv_series:
    path: ../tv_series

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^9.0.3

flutter:
