name: tv_series
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^6.0.3
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.0.0
  get_it: ^7.1.3
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  card_swiper: ^2.0.3
  intl: ^0.17.0
  flutter_advanced_drawer: ^1.3.2
  flutter_bloc: ^8.0.1
  firebase_core: ^1.19.1
  firebase_crashlytics: ^2.8.4

  core:
    path: ../core
  movie:
    path: ../movie

dev_dependencies:
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
